### ISSUE TITLE
An HTTP error 500 occurred when click

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/flag#15]
When click the flag link it brings a pop up window with the error "An HTTP error 500 occurred." but if i close that and press again then the flag works, only happend with the first click.

**The error log says:** Notice: Undefined property: stdClass::$language en línea 113 /modules/flag/flag.tokens.inc).

**Comment by laryn** [comment]
Hi @Acertijo! Can you tell me a little more about your set up? What is the flag link attached to? I'm assuming you have multiple languages enabled? Which version of Backdrop and flag do you have installed?

If you have the public release installed, could you test the latest dev version and see if it solves your issue? If so maybe we can get a new release made.

**Comment by Acertijo** [comment]
Hi, the flag link is attached to a simple article node, i am testing now in a Test site, i tried with "Display link as field" and "Display on Content Full view" and no changes, playing betwen JavaScript toggle, Normal link and Confirmation form but still the same, tried with views putting the flag as field and nothing, right now i have disabled the multi language, now the message changed, now without multi lang it shows:

"TypeError: Argument 1 passed to filter_entity_insert() must implement interface EntityInterface, instance of stdClass given, called in /home/core/includes/module.inc on line 960 en filter_entity_insert() (línea 1613 de /home/core/modules/filter/filter.module)."

Backdrop 1.14
Flag  1.x-1.0.0

**Comment by laryn** [comment]
@Acertijo Can you try this version and report back if it helps?
https://github.com/backdrop-contrib/flag/archive/1.x-1.x.zip

I see there was a change to the line your error raised:
https://github.com/backdrop-contrib/flag/commit/0199db2f93052978c675cbe435ca890cf8dc5ff9

**Comment by Acertijo** [comment]
Laryn, new version installed and now its perfect everything works great, no errors
