### ISSUE TITLE
Push a release for this module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/flag#17]
I just installed this module and it got a number of errors. 

Recognizing that the only release was almost 4 years ago and that numerous commits have been made since then, I tried the DEV release and it's working fine. 

Lots of people are afraid to use DEV releases and this is a pretty important module. Do you think we can get a new release?

**Comment by laryn** [comment]
@stpaultim I believe the currently listed maintainer is no longer active with Backdrop CMS, based on previous contact:
https://github.com/backdrop-contrib/login_destination/issues/5#issuecomment-427306114

Ah, see also: https://github.com/backdrop-contrib/flag/issues/12

**Comment by jromine** [comment]
@stpaultim I'm not using this module at present; my last commit was in 2016. Would you like to be a maintainer?

**Comment by laryn** [comment]
Since we have a release at this point, I'll close this issue.

**Comment by stpaultim** [comment]
I'm confused by my original comment, because it suggested that in Dec 2019 that there were commits in dev that are not in release. But, when I look today I see that the last commit was Oct 9, 2017 - the same day as the last release (2nd). So, my original comments don't make sense in hindsight. 

Closing this issue makes sense. I have since used this module on sites and it's worked for me.

**Comment by laryn** [comment]
There was a bug squad release in Feb 2020 which brought in some new commits I think.

**Comment by stpaultim** [comment]
Ahh, got it. I was looking at Tags, not releases. That explains things.
