### ISSUE TITLE
Tokens not working? Dependency on token module?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/flag#18]
I'm creating a flag and in the Token Replacement field, I'm getting a message that says that I don't have the token module enabled. 

According to BackdropCMS, the Token module is now included in core and I no longer have the ability to enable it. 
https://backdropcms.org/project/token

Also - I tried to add a token and it didn't work.

We should probably either resolve this issue or hide/disable this field until it's working. 

![Flags___Backdrop_CMS_Live](https://user-images.githubusercontent.com/3144571/90214308-aaa94980-ddbd-11ea-991e-1d922837138a.png)

(https://github.com/backdrop-contrib/flag/issues/12 - I understand that there is no active maintainer for this module right now, but I may be creating a few issues as I make use of the module. Not sure I have the skill to maintain it myself, but would be willing to help if someone else steps forward.)

**Comment by laryn** [comment]
In modules I've ported I've had to remove logic checking whether token was installed and just assume it was.

**Comment by herbdool** [comment]
I've removed check for token module so hopefully the tokens are visible. Can someone check?
