### ISSUE TITLE
Removing `session_api_available()` call

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/flag#26]
In [a separate thread](https://www.drupal.org/project/session_api/issues/2416313#comment-12162964) `aross` states that his previous patch includes an unnecessary call to `session_api_available()` which can prevent `flag` from working with anonymous users (and `session_api`):

> I already did some patching of session API, and what will happen now is that the module will attempt to start the session anyway (when get_sid is called). Actually, calling code shouldn't have to use session_api_available() because session_api_get_sid() already does that. I guess I didn't realize that at the time I patched Flag. What will happen is that session API "doesn't work" at the first request, but then tries to set a cookie via $_SESSION. If the client accepts that cookie and sends it with the next request, then Session API works as expected.

It sounds like this module should remove the `session_api_available()` call completely if I am reading that right.

**Comment by herbdool** [comment]
I've removed session_api_available().
