### ISSUE TITLE
Views of flaggings

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/flag#30]
I'm using flags to handle session reviews for a conference site, and I'd love to be able to see all flaggings for a specific session in the same place. This would be either on the node itself, or on a dedicated page `sessions/reviews/%` where I have set the node ID as a contextual filter.

I tried to build this using the current flag relationships, but I'm only ever able to see a single review. (This is still very useful for showing people their own reviews!)

I believe a view of flaggings is possible in Drupal 8, but for Drupal 7 I haven't found a great solution.

**Comment by bobchristenson** [comment]
Oh, glad its not just us.  Here's a newer (duplicate?) version of this problem: https://github.com/backdrop-contrib/flag/issues/39

**Comment by argiepiano** [comment]
Yes, the submodule `flag_bookmark` contains a default view that was never ported. PR coming.

**Comment by herbdool** [comment]
I think this is addressed now with https://github.com/backdrop-contrib/flag/pull/43
