### ISSUE TITLE
No Views Features Seen

### ISSUE THREAD

**Issue by ericfoy** [backdrop-contrib/flag#39]
Perhaps I'm missing something... Having installed the Flags module, no new view has been created, and I find no mention of any flags-related features within the Views interface.

**Comment by ericfoy** [comment]
I am able to setup a Bookmarks flag, the "Bookmark this" link shows up at the bottom of each node, and appears to function, but I have no way of referencing or displaying bookmarked nodes.

**Comment by bobchristenson** [comment]
Just a 'me too' here.  Flag says it comes with a sample bookmarks view...but it doesn't seem to.  At least some documentation on how to create a flag view would be great!

**Comment by argiepiano** [comment]
PR #43 ready for testing. These are the default views provided by the D7 module.

**Comment by herbdool** [comment]
Merged. Thanks @argiepiano!
