### ISSUE TITLE
jQuery.trim() is deprecated

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/flag#49]
https://api.jquery.com/jQuery.trim/

> Note: This API has been deprecated in jQuery 3.5; please use the native [String.prototype.trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) method instead. Unlike jQuery.trim, String.prototype.trim does not work with types other than strings (null, undefined, Number). Make sure that your code is compatible when migrating.

https://github.com/backdrop-contrib/flag/blob/1.x-1.x/js/flag.js#L203

**Comment by laryn** [comment]
I've linked a PR for review.

**Comment by herbdool** [comment]
Thanks @laryn merged.
