### ISSUE TITLE
Unusable duplicate breadcrumb in Views tab

### ISSUE THREAD

**Issue by MxAQue** [backdrop-contrib/flag#52]
If you go to the 'bookmarks' tab that is added by default on a user's page ('.../accounts/*/bookmarks'), the breadcrumbs of the page are by default "Home > [Username] > User bookmarks > [Username]'s bookmarks". If you click "user bookmarks", it actually takes you to a unique page for this Views tab that's titled 's bookmarks with the url '.../accounts/%2A/bookmarks', which only says "This user has not yet bookmarked any content."

This is obviously a useless page, and I wound up running into the same problem when I duplicated the 'Flag bookmarks tab' Views in order to make a similar tab for something else. However, after a lot of time hitting a bunch of random switches, I discovered how to turn it off! (I have not used Drupal in ages, and am new to Backdrop; this may be entirely obvious to others, but it was not to me and may not be for others.)

To fix;
- Open the "flag bookmarks tab" views.
- Click the "(bookmarks_user) User account: Uid" link under 'contextual filters'.
- In the "When the filter value is NOT in the URL" section, open the "Exceptions" section on the right.
- In "Exception value", put _%1_ and then save the filter and your view.
- Visit a user's public bookmarks at '.../accounts/*/bookmarks' to see your results.

Tada! The unusable breadcrumb is now gone. The breadcrumb should now read "Home > [Username] > [Username]'s bookmarks", which looks infinitely better and matches the breadcrumbs for all other tabs on the user's page. It also removes the useless link.

I have attempted to submit a patch to have this fixed by default, but I have never actually done that before, so if I did not do it right, my bad folks, I tried.

**Comment by herbdool** [comment]
Thanks @MxAQue. I've added an update hook and merged.
